#!/bin/bash

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "India Little"
git config --global user.email indialittle18@gmail.com
